
DWAPlannerROS:
    max_trans_vel: 0.55             #_default : 0.55
    min_trans_vel: 0.1             #_default : 0.1


    max_vel_x: 0.55         #0.5      #_default : 0.55
    min_vel_x: -0.55        #-0.5        #_default : 0.0


    max_vel_y: 0.1         #0.4        #_default : 0.1
    min_vel_y: -0.1        #-0.4         #_default : -0.1

    max_rot_vel: 1.5         #0.75       #_default : 1.0
    min_rot_vel: 0.15                #_default : 0.4

    acc_lim_x: 1.5 # 1.5               #_default : 2.5
    acc_lim_y: 1.5 # 1.5                #_default : 2.5
    acc_lim_theta: 3.2 # 2.5         #_default : 3.2
    acc_limit_trans: 1.5  #0.1          #default : 0.1

    #----------------------------------------------

    sim_time: 1.7                  #default : 1.7
    sim_granularity: 0.025          #default : 0.025
    angular_sim_granularity: 0.1

    goal_distance_bias: 24.0        #default : 24.0, best: 15.0
    path_distance_bias: 42.0        #default : 32.0, best: 35.0

    occdist_scale: 0.05              #default : 0.01

    stop_time_buffer: 0.2           #default : 0.2
    oscillation_reset_dist: 0.05    #default : 0.05

    forward_point_distance: 0.325    #default : 0.325

    oscillation_reset_angle: 0.2


    scaling_speed: 0.25             #default : 0.25
    max_scaling_factor: 0.2        #default : 0.2

    vx_samples: 5                   #default : 3
    vy_samples: 6                   #_default : 10
    vtheta_samples: 20              #_default : 20

    sim_period: 0.2                 #default : not found

    xy_goal_tolerance: 0.05         #default : 0.10,       best: 0.05
    yaw_goal_tolerance: 0.12        #default : 0.05,      best: 0.12
    latch_xy_goal_tolerance: false

    rot_stopped_vel: 0.02           #default : not found
    trans_stopped_vel: 0.02         #default : not found

    penalize_negative_x: false      #default : true
    use_dwa: true
    restore_defaults: false
    
    prune_plan: true #default true
    #publish_cost_grid_pc: true
    cheat_factor: 3.0
