base_frame: /base_link
map_frame: /map
odom_frame: /odom
map_update_interval: 2.0
maxUrange: 3.0
maxRange: 5.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 7
lsigma: 0.075
ogain: 3.0
lskip: 0
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.2
angularUpdate: 0.15
temporalUpdate: 3.0
resampleThreshold: 0.5
particles: 30
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.01
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
occ_thresh: 0.25
scan_topic: scan_combined
num_lasers: 2

