## -----------------------------------------
# All parameters at: wiki.ros.org/costmap_2d
## -----------------------------------------

## ---------------------------
# Costmap dependent parameters
#  - global costmap
#  - local costmap
## ---------------------------

footprint: [[0.5, 0.29], [-0.5, 0.29], [-0.5, -0.29], [0.5, -0.295]]

# --- costmap:
transform_tolerance:   0.2
publish_frequency:     2.0

resolution: 0.05

# --- obstacle layer:
#track_unknown_space:   false
publish_voxel_map:     false

obstacle_range:        1.5
raytrace_range:        1.5
max_obstacle_height:   1.2

obstacle_layer:
    observation_sources:   laser_scan

    laser_scan:
        topic:                    /scan
        sensor_frame:             hokuyo_laser_link
        data_type:                LaserScan
        observation_persistence:  0.0
        expected_update_rate:     0.4
        marking:                  true
        clearing:                 true
        min_obstacle_height:      -0.1
        max_obstacle_height:      1.2
        min_obstalce_range:       0.5
        obstacle_range:           1.5
        raytrace_range:           1.5
        inf_is_valid:             false
